spring:
  application:
    name: eureka_server
  config:
    import: optional:configserver:http://localhost:8888
  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.web: DEBUG