spring:
  application:
    name: auth_service
  config:
    import: optional:configserver:http://localhost:8888
  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.web: DEBUG
oauth:
  client-secret: ${TRADEHUB_CLIENT_SECRET}
#spring:
#  config:
#    import: optional:configserver:http://localhost:8888